name       : qdriverstation
version    : 17.01
release    : 5
source     :
    - https://github.com/FRC-Utilities/QDriverStation/archive/v17.01.tar.gz : c610a74091d6112240c0da0e6e5395fbf8de95ad379f3b27d216dd263a4de7dc
license    : MIT
component  : desktop
summary    : The QDriverStation is a cross-platform and open-source alternative to the FRC Driver Station.
description: |
    The QDriverStation is a cross-platform and open-source alternative to the FRC Driver Station. It allows you to operate FRC robots with the major operating systems (Windows, Mac OSX and GNU/Linux). The QDriverStation is able to operate both 2009-2014 robots and 2015-2016 robots.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(sdl2)
rundeps    :
    - qt5-quickcontrols
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
